import { EmployeeLeave, LeaveType, Status } from '@shared/models/leave';

export const EMPLOYEE_LEAVES: EmployeeLeave[] = [
  {
    id: 1,
    employeeId: 'EMP001',
    employeeName: 'Michael Darko',
    department: 'Engineering',
    leaveType: LeaveType.ANNUAL,
    startDate: '2025-10-10',
    endDate: '2025-10-15',
    status: Status.APPROVED,
    reason: 'Family vacation',
    daysRequested: 5,
    approver: 'Sarah Mensah',
    appliedOn: '2025-09-28',
  },
  {
    id: 2,
    employeeId: 'EMP002',
    employeeName: 'Ama Boateng',
    department: 'Human Resources',
    leaveType: LeaveType.SICK,
    startDate: '2025-10-03',
    endDate: '2025-10-05',
    status: Status.APPROVED,
    reason: 'Flu and fever',
    daysRequested: 2,
    approver: 'John Owusu',
    appliedOn: '2025-10-01',
  },
  {
    id: 3,
    employeeId: 'EMP003',
    employeeName: 'Kwesi Ntim',
    department: 'Finance',
    leaveType: LeaveType.CASUAL,
    startDate: '2025-10-07',
    endDate: '2025-10-09',
    status: Status.PENDING,
    reason: 'Personal errands',
    daysRequested: 2,
    approver: 'Abigail Kusi',
    appliedOn: '2025-10-02',
  },
  {
    id: 4,
    employeeId: 'EMP004',
    employeeName: 'Efua Owusu',
    department: 'Design',
    leaveType: LeaveType.MATERNITY,
    startDate: '2025-09-01',
    endDate: '2025-12-01',
    status: Status.APPROVED,
    reason: 'Maternity leave',
    daysRequested: 90,
    approver: 'Kofi Adjei',
    appliedOn: '2025-08-15',
  },
  {
    id: 5,
    employeeId: 'EMP005',
    employeeName: 'Yaw Asare',
    department: 'IT Support',
    leaveType: LeaveType.STUDY,
    startDate: '2025-11-10',
    endDate: '2025-11-20',
    status: Status.REJECTED,
    reason: 'Request outside allowed study leave period',
    daysRequested: 10,
    approver: 'Sarah Mensah',
    appliedOn: '2025-10-15',
  },
];
