import { EmployeeLeave, LeaveType, Status } from '@shared/models/leave';

export const EMPLOYEE_LEAVES: EmployeeLeave[] = [
  {
    id: 1,
    employeeId: 'EMP001',
    employeeName: 'Michael Darko',
    department: 'Engineering',
    leaveType: LeaveType.ANNUAL,
    startDate: '2025-10-10',
    endDate: '2025-10-15',
    status: Status.APPROVED,
    reason: 'Family vacation',
    daysRequested: 5,
    approver: 'Sarah Mensah',
    appliedOn: '2025-09-28',
  },
  {
    id: 2,
    employeeId: 'EMP002',
    employeeName: 'Ama Boateng',
    department: 'Human Resources',
    leaveType: LeaveType.SICK,
    startDate: '2025-10-03',
    endDate: '2025-10-05',
    status: Status.APPROVED,
    reason: 'Flu and fever',
    daysRequested: 2,
    approver: 'John Owusu',
    appliedOn: '2025-10-01',
  },
  {
    id: 3,
    employeeId: 'EMP003',
    employeeName: 'Kwesi Ntim',
    department: 'Finance',
    leaveType: LeaveType.CASUAL,
    startDate: '2025-10-07',
    endDate: '2025-10-09',
    status: Status.PENDING,
    reason: 'Personal errands',
    daysRequested: 2,
    approver: 'Abigail Kusi',
    appliedOn: '2025-10-02',
  },
  {
    id: 4,
    employeeId: 'EMP004',
    employeeName: 'Efua Owusu',
    department: 'Design',
    leaveType: LeaveType.MATERNITY,
    startDate: '2025-09-01',
    endDate: '2025-12-01',
    status: Status.APPROVED,
    reason: 'Maternity leave',
    daysRequested: 90,
    approver: 'Kofi Adjei',
    appliedOn: '2025-08-15',
  },
  {
    id: 5,
    employeeId: 'EMP005',
    employeeName: 'Yaw Asare',
    department: 'IT Support',
    leaveType: LeaveType.STUDY,
    startDate: '2025-11-10',
    endDate: '2025-11-20',
    status: Status.REJECTED,
    reason: 'Request outside allowed study leave period',
    daysRequested: 10,
    approver: 'Sarah Mensah',
    appliedOn: '2025-10-15',
  },
  {
    id: 1,
    employeeId: 'EMP001',
    employeeName: 'Michael Darko',
    department: 'Engineering',
    leaveType: LeaveType.ANNUAL,
    startDate: '2025-01-13',
    endDate: '2025-01-17',
    status: Status.APPROVED,
    reason: 'Annual vacation to rest and recharge.',
    daysRequested: 5,
    approver: 'Sarah Osei',
    appliedOn: '2025-01-03',
  },
  {
    id: 2,
    employeeId: 'EMP002',
    employeeName: 'Emmanuella Owusu',
    department: 'Human Resources',
    leaveType: LeaveType.SICK,
    startDate: '2025-02-03',
    endDate: '2025-02-05',
    status: Status.PENDING,
    reason: 'Medical recovery from flu.',
    daysRequested: 3,
    approver: 'Samuel Boateng',
    appliedOn: '2025-02-01',
  },
  {
    id: 3,
    employeeId: 'EMP003',
    employeeName: 'Kwabena Ofori',
    department: 'Finance',
    leaveType: LeaveType.CASUAL,
    startDate: '2025-03-10',
    endDate: '2025-03-12',
    status: Status.APPROVED,
    reason: 'Personal family matters.',
    daysRequested: 3,
    approver: 'Patricia Asiedu',
    appliedOn: '2025-03-05',
  },
  {
    id: 4,
    employeeId: 'EMP004',
    employeeName: 'Linda Mensah',
    department: 'Operations',
    leaveType: LeaveType.MATERNITY,
    startDate: '2025-04-01',
    endDate: '2025-07-01',
    status: Status.APPROVED,
    reason: 'Maternity leave after childbirth.',
    daysRequested: 92,
    approver: 'Evelyn Nartey',
    appliedOn: '2025-03-20',
  },
  {
    id: 5,
    employeeId: 'EMP005',
    employeeName: 'Yaw Appiah',
    department: 'IT Support',
    leaveType: LeaveType.STUDY,
    startDate: '2025-05-15',
    endDate: '2025-06-10',
    status: Status.REJECTED,
    reason: 'Request denied due to ongoing system migration project.',
    daysRequested: 27,
    approver: 'Michael Darko',
    appliedOn: '2025-05-10',
  },
  {
    id: 6,
    employeeId: 'EMP006',
    employeeName: 'Abigail Adu',
    department: 'Marketing',
    leaveType: LeaveType.ANNUAL,
    startDate: '2025-06-20',
    endDate: '2025-06-30',
    status: Status.PENDING,
    reason: 'Traveling for vacation.',
    daysRequested: 11,
    approver: 'Sarah Osei',
    appliedOn: '2025-06-10',
  },
  {
    id: 7,
    employeeId: 'EMP007',
    employeeName: 'John Asante',
    department: 'Engineering',
    leaveType: LeaveType.SICK,
    startDate: '2025-07-14',
    endDate: '2025-07-18',
    status: Status.APPROVED,
    reason: 'Medical recovery from minor surgery.',
    daysRequested: 5,
    approver: 'Evelyn Nartey',
    appliedOn: '2025-07-10',
  },
  {
    id: 8,
    employeeId: 'EMP008',
    employeeName: 'Doris Agyemang',
    department: 'Customer Service',
    leaveType: LeaveType.CASUAL,
    startDate: '2025-08-02',
    endDate: '2025-08-03',
    status: Status.REJECTED,
    reason: 'Insufficient leave balance and short notice.',
    daysRequested: 2,
    approver: 'Samuel Boateng',
    appliedOn: '2025-07-30',
  },
  {
    id: 9,
    employeeId: 'EMP009',
    employeeName: 'Richard Owusu',
    department: 'Finance',
    leaveType: LeaveType.PATERNITY,
    startDate: '2025-09-10',
    endDate: '2025-09-15',
    status: Status.APPROVED,
    reason: 'To support spouse after childbirth.',
    daysRequested: 6,
    approver: 'Patricia Asiedu',
    appliedOn: '2025-09-05',
  },
  {
    id: 10,
    employeeId: 'EMP010',
    employeeName: 'Naomi Boateng',
    department: 'Human Resources',
    leaveType: LeaveType.STUDY,
    startDate: '2025-10-01',
    endDate: '2025-10-10',
    status: Status.PENDING,
    reason: 'Attending a leadership development workshop.',
    daysRequested: 10,
    approver: 'Sarah Osei',
    appliedOn: '2025-09-20',
  },
];
